// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"net/http"
)

import (
	_ "github.com/joho/godotenv"
)

// Injectors from wire.go:

func InitializeServer() *http.Server {
	server := NewServer()
	return server
}
