// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/labstack/echo"
	"moviesnow-backend/app"
)

// Injectors from wire.go:

func InitializeServer() *echo.Echo {
	router := app.NewRouter()
	echoEcho := app.NewServer(router)
	return echoEcho
}
